version: '3.8'

services:
  backend:
    image: batatadoc3/quippercodecompiler-backend:latest
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  frontend:
    image: batatadoc3/quippercodecompiler-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend