version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: ./QuipperCodeCompiler.Server
      dockerfile: Dockerfile 
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_HTTP_PORTS=8080

  frontend:
    image: frontend-image
    build:
      context: ./quippercodecompiler.client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend